kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: scc-statefulset-gitea-default
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
allowedCapabilities:
- CAP_CHOWN
groups:
- system:cluster-admins
- system:nodes
fsGroup:
  type: MustRunAs
  ranges:
    - min: 1000
      max: 1000
runAsUser:
  type: MustRunAs
  uid: 1000
seLinuxContext:
  type: RunAsAny
users:
- system:serviceaccount:gitea:default