apiVersion: config.porch.kpt.dev/v1alpha1
kind: Repository
metadata:
  name: catalog-workloads-tools
  namespace: default
  labels:
    kpt.dev/repository-access: read-only
    kpt.dev/repository-content: external-blueprints
spec:
  content: Package
  deployment: false
  git:
    branch: R3
    directory: /workloads/tools
    repo: https://github.com/JaehoKwak/catalog.git
  type: git
